### ISSUE TITLE
Attach files option not availble in cake mail addin

### ISSUE THREAD

**Issue by VQuery** [cake-contrib/Cake.CakeMail#16]
I am using Cake.Email addin for sending mail to multiple recipents but i need to attach some documents while sending mail.
I think we don't have this feature .So please add this option in Cake.Email addin .It will be very useful too

**Comment by gep13** [comment]
Created in wrong repository.  Was re-created here: https://github.com/cake-contrib/Cake.Email/issues/16

**Comment by Jericho** [comment]
CakeMail does not allow attachments therefore this feature can not be added to this addin.
